### ISSUE TITLE
Default num threads

### ISSUE THREAD

**Issue by mloubout** [ChevronETC/AzManagers.jl#22]
In `addprocs` the default `omp_num_threads=get(ENV, "OMP_NUM_THREADS", 1)` will reutrn a `String` if `OMP_NUM_THREADS`  is defined while it is expected to be an Int later on.

**Comment by samtkaplan** [comment]
Thanks for reporting this!  The fix should be in PR #23.

**Comment by mloubout** [comment]
Cool, thanks.
